### ISSUE TITLE
Rate errors in individual repositories as Warning

### ISSUE THREAD

**Issue by ckunki** [exasol/error-catalog#49]
Currently, GitHub workflow [Deploy to GitHub pages](https://github.com/exasol/error-catalog/blob/main/.github/workflows/deploy-to-github-pages.yml) fails, e.g. [here](https://github.com/exasol/error-catalog/actions/runs/11677299758/job/32514962335#step:4:3651) with

```
2024-11-05 04:01:01.749 [INFO   ] Found 0 releases for 'advanced-analytics-framework' (123/123) 
java.lang.IllegalStateException: E-EC-3: Failed download error-code report.
at ...ErrorReportDownloader.downloadReportIfNotExists(ErrorReportDownloader.java:55)
at ...ErrorReportCollector.collectReports(ErrorReportCollector.java:35)
at ...ErrorCatalog.run(ErrorCatalog.java:57)
at ...ErrorCatalog.main(ErrorCatalog.java:44)
```

Caused by: java.io.IOException: Server returned HTTP response code: 403 for [URL](https://objects.githubusercontent.com/github-production-release-asset-2e65be/297929223/6de938b1-6aeb-457d-87cc-c4585d0bb2d6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241105%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241105T040032Z&X-Amz-Expires=300&X-Amz-Signature=35cf1041ed9384f9d3b3da4f2e834655023fa3802d197fdf56786cb84c56105c&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Derror_code_report.json&response-content-type=application%2Foctet-stream): 
```	
at ...ErrorReportDownloader.downloadReport(ErrorReportDownloader.java:75)
at ...ErrorReportDownloader.downloadReportIfNotExistsInternal(ErrorReportDownloader.java:67)
at ...ErrorReportDownloader.downloadReportIfNotExists(ErrorReportDownloader.java:52)
... 11 more
Error:  Command execution failed.
```

**Comment by ckunki** [comment]
### Proposal

* Change method [ErrorReportDownloader.downloadReportIfNotExists()](https://github.com/exasol/error-catalog/blob/main/src/main/java/com/exasol/errorcodecatalog/collector/ErrorReportDownloader.java#L50) to
  * return `Optional<Path>`
  * if download fails, then log a warning and return `Optional.empty()`
* Change [ErrorReportCollector.collectReports()](https://github.com/exasol/error-catalog/blob/main/src/main/java/com/exasol/errorcodecatalog/collector/ErrorReportCollector.java#L35) to ignore empty returns of `downloadReportIfNotExists()`
* Update and add related tests

**Comment by ckunki** [comment]
In the scope of #46 the error message has been improved. 
We currently assume only sporadic failures, i.e. the next execution will be successful.
We decided to wait until the problem occurs again.
